### ISSUE TITLE
Is it possible to run proxy on CPU without AES-NI ?

### ISSUE THREAD

**Issue by KavkaTSR** [Snipa22/xmr-node-proxy#10]
I've got error while installing installing on AMD Opteron based server.
While compiling xmr-node-proxy:
```
.... /include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
```
Is it possible to run proxy on CPU without AES-NI ?

**Comment by Snipa22** [comment]
You'd need to manually install a compatible version of node-multi-hashing, something along the lines of: https://github.com/zone117x/node-multi-hashing  I've not checked what versions of NaN this is compatible with though.
