### ISSUE TITLE
api web status

### ISSUE THREAD

**Issue by FranzDE** [Snipa22/xmr-node-proxy#124]
Hello everyone, I've been searching the net for days but I can not find any web interface to connect with the xmr-node-proxy API.
Which web interface do you use to monitor the proxy? thank you

**Comment by Ethorsen** [comment]
You should look into this PR for a monitoring server

https://github.com/Snipa22/xmr-node-proxy/pull/111

**Comment by FranzDE** [comment]
thanks!
