### ISSUE TITLE
TypeError: Cannot read property 'blobForWorker' of null

### ISSUE THREAD

**Issue by sx5486510** [Snipa22/xmr-node-proxy#15]
hi,i always got an error
`TypeError: Cannot read property 'blobForWorker' of null
1|proxy    |     at Object.getMasterJob (/home/shen/xmr-node-proxy/lib/xmr.js:136:37)
1|proxy    |     at EventEmitter.masterMessageHandler (/home/shen/xmr-node-proxy/proxy.js:67:50)
1|proxy    |     at emitThree (events.js:116:13)
1|proxy    |     at EventEmitter.emit (events.js:194:7)
1|proxy    |     at Worker.<anonymous> (cluster.js:362:15)
1|proxy    |     at emitTwo (events.js:111:20)
1|proxy    |     at Worker.emit (events.js:191:7)
1|proxy    |     at ChildProcess.Worker.process.on (cluster.js:53:12)
1|proxy    |     at emitTwo (events.js:106:13)
1|proxy    |     at ChildProcess.emit (events.js:191:7)`

 the proxy restart again and again, pm2 restart no work.

**Comment by Snipa22** [comment]
Are you using a pool listed on the main page?  If there's no blobForWorker, it would suggest that the system isn't downloading a new work job fast enough, and/or you're connecting to a pool that isn't supported.

Any pool running a recent version of nodejs-pool should work.

**Comment by sx5486510** [comment]
i use supportxmr.com, Normal work at ordinary times,, always down

**Comment by Snipa22** [comment]
You'll want to speak with their administration directly, other people are using the proxy fine at the moment with supportxmr.com.

**Comment by sx5486510** [comment]
i checked with m5m, but he didn't know what happen and told me ask u for help

**Comment by Snipa22** [comment]
Please check in with me on IRC in that case.  The proxy is working fine w/ supportxmr.com at the moment.

**Comment by sx5486510** [comment]
i got the reason, if u send needPoolState to worker, but u haven't login pool, pool.activeBlocktemplate is NULL, and whe worker crush
