### ISSUE TITLE
CryptonightR support?

### ISSUE THREAD

**Issue by 2010phenix** [Snipa22/xmr-node-proxy#161]
what with support new Monero update Mach 7 ?

**Comment by Romeo1984** [comment]
+1 Please provide update. Thanks!

**Comment by acidx0** [comment]
+1 Please provide support

**Comment by uncher** [comment]
> +1 Please provide support

Try https://github.com/MoneroOcean/xmr-node-proxy

**Comment by Snipa22** [comment]
This was done a week ago.
