### ISSUE TITLE
Can't build multi-hashing

### ISSUE THREAD

**Issue by tosokr** [Snipa22/xmr-node-proxy#18]
On npm install there is a built error. I tried with several versions of node, but no luck. Using Ubuntu Server 16.04.2 VM 

/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^
../cryptonight.c:71:7: error: called from here
  tmp4 = _mm_aeskeygenassist_si128(*tmp1, 0x00);

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tosokr/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "node" "/home/tosokr/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tosokr/xmr-node-proxy/node_modules/multi-hashing
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional dep failed, continuing multi-hashing@0.0.10

**Comment by Snipa22** [comment]
Your processor likely doesn't have AES-NI available, please use a modern x86_64 processor w/ AES-NI available.  Alternatively, you can look into some of the other muiltihashing libs: https://github.com/zone117x/node-multi-hashing though I've not compiled it in quite some time.
