### ISSUE TITLE
pm2: command not found

### ISSUE THREAD

**Issue by drshell60** [Snipa22/xmr-node-proxy#19]
After finising all steps i got this guys ! 

No command 'pm2' found, did you mean:
 Command 'pmi' from package 'powermanagement-interface' (universe)
 Command 'pm' from package 'powerman' (universe)
 Command 'fpm2' from package 'fpm2' (universe)
 Command 'pms' from package 'pms' (universe)
 Command 'pmw' from package 'pmw' (universe)
 Command 'pom2' from package 'libpod-pom-perl' (universe)
 Command 'wm2' from package 'wm2' (universe)
 Command 'pmk' from package 'pmk' (universe)
pm2: command not found

**Comment by slayerulan** [comment]
Run:
`source ~/.bashrc`
