### ISSUE TITLE
Problem when proxy public IP address is changed

### ISSUE THREAD

**Issue by tosokr** [Snipa22/xmr-node-proxy#21]
When the public IP address of the proxy is changed, while the proxy is working, the log is full with this errors:

0|mproxy   | 2017-08-06 22:48 +02:00: Error response from pool pool.supportxmr.com: {"code":-1,"message":"Invalid job id"}
0|mproxy   | Error response from pool pool.supportxmr.com: {"code":-1,"message":"Invalid job id"}
0

Regards

**Comment by Snipa22** [comment]
This would be because the system isn't going to play nicely with this.  Restart the proxy if you change public IP addresses.  Invalid Job ID means that proxy doesn't agree with the jobID from the pool.
