### ISSUE TITLE
 Error: Cannot find module 'cryptonote-util'

### ISSUE THREAD

**Issue by Alex378563872624837** [Snipa22/xmr-node-proxy#23]
Hi,

I followed the instructions and installed your software on a Ubuntu 16.04 64bit. After starting I see a lot of the following error messages:
1|proxy    | 2017-08-10 15:45 +02:00: Error: Cannot find module 'cryptonote-util'
1|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
1|proxy    |     at Function.Module._load (module.js:417:25)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:3:16)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)
What can I do?

**Comment by Snipa22** [comment]
Were there any error messages with the rest of the installer?  This would suggest missing libraries, as CN-Util is based on lib-boost and comes from the Monero source.

**Comment by Alex378563872624837** [comment]
Hi thanks for the reply. I noticed a few warnings but no error during installation, but I can't really say because I did not follow the steps by hand, but used your provided script.

**Comment by Alex378563872624837** [comment]
Can I run the commands of your script one-by-one? Or is there something that will fail the 2nd time?

**Comment by Snipa22** [comment]
It would be the npm install command.

**Comment by shod4n** [comment]
I'm experiencing exactly the same error as above. I've tried to install the proxy via the provided script twice on two fresh servers with Ubuntu 16.04 (hosted at Amazon EC2). It still shows Error: Cannot find module 'cryptonote-util'

Any possible solution?

**Comment by Snipa22** [comment]
T2 Micros require that you load up some swap.  You'll need to create a local swap disk, and mount that as swap.

**Comment by shod4n** [comment]
Thanks, I've already solved it by provisioning a better VM at GCloud with more memory (3.75 GB was enough).

**Comment by dorimanx** [comment]
Hi, running T2 micro server at amazon cloud! with 1GB ram.
50 miners connected!
7000h/s total.
===========
ubuntu@ip-172-31-36-248:~$ free
              total        used        free      shared  buff/cache   available
Mem:        1014656      250736      136220        8248      627700      547340
Swap:             0           0           0
ubuntu@ip-172-31-36-248:~$
===========
No issues!
DORI-FARM                      Mem:  52 MB    CPU:  0 %  online
EC2-SWARM                      Mem:  51 MB    CPU:  0 %  online
pm2-logrotate                  Mem:  38 MB    CPU:  0 %  online

Not sure how much miners it's will hold. but for 50 it's OK.

**Comment by Alex378563872624837** [comment]
Thanks for the answer. It seems  that 768MB RAM and a small swap is not enough. Unfortunately I can't increase the swap, so I will have to try on a different machine. 

Thanks for the help
