### ISSUE TITLE
pool suuport

### ISSUE THREAD

**Issue by mik2141797** [Snipa22/xmr-node-proxy#27]
Is the pool monero.crypto-pool.fr supprot? thx

**Comment by dorimanx** [comment]
Please add support for http://dwarfpool.com/

Tried to work with monero.crypto-pool.fr or dwarfpool.com and getting errors in monitor.

Thanks!

**Comment by Snipa22** [comment]
These pools have to add support to their source code.  They do not implement the stratum access required in order to use the xmr-node-proxy.  Please use one of the supported pools listed in the readme.
