### ISSUE TITLE
TypeError: Cannot read property 'activeBlocktemplate'

### ISSUE THREAD

**Issue by BamaStangGuy** [Snipa22/xmr-node-proxy#28]
Any ideas? Using CCMiner with following info:

ccminer-x64 -a cryptonight -o stratum+tcp://xx.xx.xx.xx:8080 -u monero address -p proxy:xxxxxxx@protonmail.com

Once CCminer is started I can see it trying to connect as in below

`x
x                                           xx xxxxxxx > 15-08-2017 21:55 +00:00: TypeError: Cannot read property 'activeBlocktemplate'  x
x                                           xx  of undefined                                                                                         x
x                                           xx xxxxxxx >     at new Miner (/home/miner/xmr-node-proxy/proxy.js:744:31)                   x
x                                           xx xxxxxxx >     at handleMinerData (/home/miner/xmr-node-proxy/proxy.js:831:21)             x
x                                           xx xxxxxxx >     at handleMessage (/home/miner/xmr-node-proxy/proxy.js:966:13)               x
x                                           xx xxxxxxx >     at Socket.<anonymous> (/home/miner/xmr-node-proxy/proxy.js:1024:25)         x
x                                           xx xxxxxxx >     at emitOne (events.js:96:13)                                                x
x                                           xx xxxxxxx >     at Socket.emit (events.js:188:7)                                            x
x                                           xx xxxxxxx >     at readableAddChunk (_stream_readable.js:176:18)                            x
x                                           xx xxxxxxx >     at Socket.Readable.push (_stream_readable.js:134:10)                        x
x                                           xx xxxxxxx >     at TCP.onread (net.js:548:20) `

**Comment by amelora** [comment]
Any update on this issue?

Got it too with a fresh install.

**Comment by Snipa22** [comment]
Nope.  What pools are in-use?  And did you remember to set a default pool in your config?

**Comment by amelora** [comment]
My bad!

Removed the second pool in the example config without noticing that it was the one by default.

**Comment by jmusac** [comment]
Have the same error, but i have only one pool in config file

**Comment by JerichoJones** [comment]
If you remove the 2nd pool make sure you set default to TRUE in the remaining pool.
