### ISSUE TITLE
2017-08-16 00:22 +00:00: Error: Cannot find module 'cryptonote-util'

### ISSUE THREAD

**Issue by BamaStangGuy** [Snipa22/xmr-node-proxy#29]
Steps to reproduce:

Start new aws t2.micro using Ubuntu 16.04
Follow instructions on github page

`/home/miner/.pm2/logs/proxy-error-1.log last 15 lines:
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)
1|proxy    | 2017-08-16 00:22 +00:00: Error: Cannot find module 'cryptonote-util'
1|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
1|proxy    |     at Function.Module._load (module.js:417:25)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/miner/xmr-node-proxy/lib/xmr.js:3:16)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)`

**Comment by Alex378563872624837** [comment]
Hi, I had the same problem (with 768MB RAM and 400MB SWAP). Try to increase RAM/swap or copy the files from a different PC.

**Comment by Tormiasz** [comment]
Did you solve the issue? I have it too, I've got 2Gb of RAM so it's not an issue

**Comment by krttrn** [comment]
I've encountered the same issue. Make sure to run the following commands before doing the git clone and install:

sudo dd if=/dev/zero of=/swapfile bs=512MB count=8

sudo chmod 600 /swapfile

sudo mkswap /swapfile

sudo swapon /swapfile
 
After you've succesfully created the swapfile, you may clone, install and configure.

Good luck!

**Comment by jmusac** [comment]
I have same problem. Using Ubuntu 16.04 TLS
After installation and running command pm2 start proxy.js i get this in logs

1|proxy    | 2017-09-06 09:17 +02:00: Cluster master setting up 1 workers...
1|proxy    | 2017-09-06 09:17 +02:00: Error: Cannot find module 'cryptonote-util'
1|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
1|proxy    |     at Function.Module._load (module.js:417:25)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:3:16)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)

Also during installation there were few errors
Creating default alias: default -> v6.9.2
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: Cloning into bare repository '/home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a'...
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: github.com[0: 192.30.253.112]: errno=Connection refused
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: github.com[1: 192.30.253.113]: errno=Connection refused
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**Comment by Snipa22** [comment]
```
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: github.com[1: 192.30.253.113]: errno=Connection refused
```
The issue here is that your box was unable to connect to github for a download.  That's something you'd need to check on locally.  You should be able to do a npm install in the xmr-node-proxy folder to fix and reinstall.

**Comment by jmusac** [comment]
The problem was that my firewall filtered port 9418 used by git protocol. That's why git clone http:// commands were working but git clone git:// didn't
