### ISSUE TITLE
error firstime used

### ISSUE THREAD

**Issue by mhejek** [Snipa22/xmr-node-proxy#34]
1|proxy    | Started server on port: 3333
1|proxy    | 2017-08-24 00:39 -07:00: Received new block template from xmr-usa.dwarfpool.com
1|proxy    | 2017-08-24 00:39 -07:00: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
1|proxy    |     at fromObject (buffer.js:262:9)
1|proxy    |     at Function.Buffer.from (buffer.js:101:10)
1|proxy    |     at new Buffer (buffer.js:80:17)
1|proxy    |     at new MasterBlockTemplate (/home/vicky/xmr-node-proxy/lib/xmr.js:88:19)
1|proxy    |     at handleNewBlockTemplate (/home/vicky/xmr-node-proxy/proxy.js:696:32)
1|proxy    |     at handlePoolMessage (/home/vicky/xmr-node-proxy/proxy.js:673:17)
1|proxy    |     at Socket.socket.on.e (/home/vicky/xmr-node-proxy/proxy.js:636:17)
1|proxy    |     at emitOne (events.js:96:13)
1|proxy    |     at Socket.emit (events.js:188:7)
1|proxy    |     at readableAddChunk (_stream_readable.js:176:18)

**Comment by Snipa22** [comment]
Dwarfpool is not supported, please use a listed supported pool.
