### ISSUE TITLE
│                                                ││ proxy > 2017-08-27 11:47 +00:00: Socket Error from undefined Error: read ETIMEDOUT                               │

### ISSUE THREAD

**Issue by xmrminer2017** [Snipa22/xmr-node-proxy#35]
│                                                ││ proxy > 2017-08-27 11:47 +00:00: Socket Error from undefined Error: read ETIMEDOUT                               │

│                                                ││ proxy > 2017-08-27 11:46 +00:00: Socket Error from 80.109.231.33 Error: write EPIPE                              │

Please help me

![capture](https://user-images.githubusercontent.com/31385245/29749525-561b5d82-8b58-11e7-8220-6b14b06c7cdb.PNG)

**Comment by Snipa22** [comment]
Timeouts and EPIPEs like these are your remote nodes disconnecting due to timeout and/or pipe errors, where the TCP connection drops.  You would want to look into why your having networking issues.
