### ISSUE TITLE
Allow shares to be split to different wallets in same pool.

### ISSUE THREAD

**Issue by dorimanx** [Snipa22/xmr-node-proxy#40]
Hi,
I have tested if proxy can share balance 50%/50% to 2 different wallets on same pool.
and it's not working.
If i set different pools it's works perfect.

part of config:

{
  "pools": [
    {
      "hostname": "pool.supportxmr.com",
      "port": 5555,
      "ssl": false,
      "allowSelfSignedSSL": false,
      "share": 90,
      "username": "WALLET #1",
      "password": "NAME#1",
      "keepAlive": true,
      "coin": "xmr",
      "default": true
    },
    {
      "hostname": "pool.supportxmr.com",
      "port": 3333,
      "ssl": false,
      "allowSelfSignedSSL": false,
      "share": 10,
      "username": "WALLET #2",
      "password": "NAME #2",
      "keepAlive": true,
      "coin": "xmr",
      "default": true
    }
  ],

**Comment by Snipa22** [comment]
The proxy was not designed to do this.  It uses the hostname of the pool as a unique key to track and manage miners through.  It's not a feature that I would find to be particularly useful.

**Comment by dorimanx** [comment]
I see thanks for your time.

**Comment by marki555** [comment]
In that case you can either try the hostname with different case (if the compare is case sensitive), for example pool.supportXMR.com. The other option is using your domain DNS and point it as CNAME to your pool. Both ways, it would look as separate pools to the proxy code.
