### ISSUE TITLE
Request: Non-root application

### ISSUE THREAD

**Issue by vKnmnn** [Snipa22/xmr-node-proxy#41]
Please make the proxy not depend on any privileged action
Or, kindly help me set up a proxy on a machine i dont have privileges on

Regards

**Comment by Snipa22** [comment]
You require root privs to install packages, nothing else.  The proxy isn't dependent on root for running.

**Comment by vKnmnn** [comment]
alright, then i might have misread the readme. 
what about creating proxy-user though? cannot do that without root.

**Comment by Snipa22** [comment]
If you already have a non-prived user, the proxy doesn't require a special one.  You /do/ require root for package installations though, nothing can get around that, unless you're willing to do manual compiles, and most restricted envs won't come with compilers.

**Comment by Snipa22** [comment]
Then I'll be closing this issue.  You'll need to rebuild a large number of packages for this.  Also, the install script doesn't use /usr/ at all.  

```
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
sudo DEBIAN_FRONTEND=noninteractive apt-get -y install git python-virtualenv python3-virtualenv curl ntp build-essential screen cmake pkg-config libboost-all-dev libevent-dev libunbound-dev libminiupnpc-dev libunwind8-dev liblzma-dev libldns-dev libexpat1-dev libgtest-dev libzmq3-dev
```
Are the only sudo enabled lines.  Good luck!
