### ISSUE TITLE
can't bind 443 port

### ISSUE THREAD

**Issue by PQFitz** [Snipa22/xmr-node-proxy#46]
Hi Bro!

Ubuntu 16.04

Ordinary users do not have permission to bind 443 ports.
The script will run out of error.
How do you think ROOT permissions start? 
Thank you very much!

**Comment by dorimanx** [comment]
Just to add to this any port with 3 or less numbers cant be binded. Any 4 numbers works.

**Comment by PQFitz** [comment]
Thank you! 
Is there a solution?

**Comment by Snipa22** [comment]
Run: sudo setcap cap_net_bind_service=+ep `which node`
As the non-priv user.
Restart PM2 and your proxy, and it should be able to bind below 443.

**Comment by PQFitz** [comment]
The problem is solved. That's great!

**Comment by PQFitz** [comment]
I recommend adding it to the installation script

sudo setcap cap_net_bind_service=+ep /home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node
