### ISSUE TITLE
cryptonode Make error

### ISSUE THREAD

**Issue by SandPox** [Snipa22/xmr-node-proxy#56]
make: Entering directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<anonymous struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:114: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node" "/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

OS: Debian 9

**Comment by SandPox** [comment]
Apparently it's the same of issue in https://github.com/zone117x/node-cryptonote-pool/issues/175

**Comment by DelphinusQuercus** [comment]
Probably the easiest way to solve this problem is to change the cryptonote-util/src/crypto/crypto.cpp line which calculates the full rs_comm size:
```
//    return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
    return sizeof(rs_comm) + pubs_count * 2 * sizeof(ec_point); /* BEWARE: Dependent on rs_comm definition above! */
```
The rs_comm struct is defined several lines above, and the anonymous struct ab[] consists of two ec_points. This will work properly with gcc-6 (and any other, as this is very simple C formulation).

**Comment by diegofcv** [comment]
Hi, have this exactly problem.
I tried to use the solution, unpacking  ~/.npm/cryptonote-util/0.0.3/package.tgz , editing cryptonote-util/src/crypto/crypto.cpp, re-packing the tgz, but when I try npm install again, it's like the change didn't apply. 
Can you give me any hint please?
