### ISSUE TITLE
Network errors aren't handled

### ISSUE THREAD

**Issue by passnet** [Snipa22/xmr-node-proxy#68]
I've tested 2 pool setup where 2nd are supposed to be failover pool. When I've used iptables REJECT rule to block all INPUT and OUTPUT traffic to main pool. But the proxy still keeps sending jobs to that pool and doesn't switches to another like nothing happened:

`2017-12-05 11:20 +03:00: Tue, 05 Dec 2017 08:20:39 GMT pool Sent {"method":"submit","id":..."}} to pool.supportxmr.com`

Looking at the code (I'm not experinced with JS) seems like poolSocket() doesn't handles this for some reason. And both Pool.sendShare and Pool.heartbeet doesn't seems to check for server response. Server aren't sending 'OK's but the proxy are still keep sending shares to 'dead' pool.

Also, what does 'default' pool configuration parameter means? This isn't documented and I don't really understand what does it means from the code.

**Comment by Snipa22** [comment]
For your default question: https://github.com/Snipa22/xmr-node-proxy/wiki/config_review

As for the REJECT, that's expected, you're not breaking the TCP connection, which is what it's waiting for.  Once the TCP connection dies, it'll cycle off to another pool.
