### ISSUE TITLE
TypeError in readableAddChunk

### ISSUE THREAD

**Issue by creolis** [Snipa22/xmr-node-proxy#8]
Hey,

I tried to use xmr-node-proxy on two different stratum pools, but it fails to work on the second one due to a TypeError. Any hints?

> 1|proxy    | 2017-07-18 07:01 +00:00: Master connected to pool: pool.supportxmr.com
> 1|proxy    | 2017-07-18 07:01 +00:00: Received new block template from pool.supportxmr.com
> 1|proxy    | 2017-07-18 07:01 +00:00: Master connected to pool: monerohash.com
> 1|proxy    | 2017-07-18 07:01 +00:00: Received new block template from monerohash.com
> 1|proxy    | 2017-07-18 07:01 +00:00: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
> 1|proxy    |     at fromObject (buffer.js:262:9)
> 1|proxy    |     at Function.Buffer.from (buffer.js:101:10)
> 1|proxy    |     at new Buffer (buffer.js:80:17)
> 1|proxy    |     at new MasterBlockTemplate (/home/operations/xmr-node-proxy/lib/xmr.js:88:19)
> 1|proxy    |     at handleNewBlockTemplate (/home/operations/xmr-node-proxy/proxy.js:670:32)
> 1|proxy    |     at handlePoolMessage (/home/operations/xmr-node-proxy/proxy.js:647:17)
> 1|proxy    |     at Socket.socket.on.e (/home/operations/xmr-node-proxy/proxy.js:610:17)
> 1|proxy    |     at emitOne (events.js:96:13)
> 1|proxy    |     at Socket.emit (events.js:188:7)
> 1|proxy    |     at readableAddChunk (_stream_readable.js:176:18)

**Comment by Snipa22** [comment]
Monerohash doesn't use the new stratum impl required for this proxy to work properly.

**Comment by Snipa22** [comment]
Readme updated with several new notes about what pools are/aren't supported that we know of at this time.
