### ISSUE TITLE
XRM Node Proxy + Stratum (Nicehash)

### ISSUE THREAD

**Issue by owii123** [Snipa22/xmr-node-proxy#83]
Hello,

My Problem is: The difficulty is set to high for my CPU-Miner, so many of my Shares are to late submitted - in fact: The service already set my Server to "not more active" sometimes.

After i got some more Servers i found out, that your Proxy can share the difficulty between the Workers!

Well, everything is working fine with normal pools but as soon i add this "stratum+tcp://"-PoolAdress i get Problems. Is there some way to solve this?

`proxy    |  2017-12-23 09:12 +01:00: 
Master Socket error from stratum+tcp://cryptonight.eu.nicehash.com 
Error: getaddrinfo EAI_AGAIN stratum+tcp://cryptonight.eu.nicehash.com:3355`

**Comment by bobbieltd** [comment]
I think xmr-node-proxy isn't compatible with nicehash. It only works with nodejs-pool and nicehash isn't nodejs-pool.

**Comment by owii123** [comment]
Thanks for the Quick reply!

But is there any other Proxy that can reduce the Worker diff?

If i look here: https://github.com/xmrig/xmrig-proxy/wiki/Comparison

XRM Node Proxy is the only one?

**Comment by bobbieltd** [comment]
XMR Node Proxy is the ONLY ONE. No proxy can connect with NiceHash. In fact, NiceHash is a proxy. You CAN NOT connect proxy to proxy at the moment.

**Comment by bobbieltd** [comment]
If you need to mine with NiceHash, the only option now is to connect your miners directly to nicehash address ( extremely high difficulty ).

**Comment by bobbieltd** [comment]
If you find my answers correct, please close your issue. Thank you.

**Comment by owii123** [comment]
Well i guess thats not 100% True if i google "proxy to proxy" :)

But anyway - after its not an intended feature, i guess its no "Issue" but more are "Wish" from me then :D 

Well: Its a Shame! Couse in fact: The earning are not Bad but 20% - 50% of my results never reach Nicehash couse of the high difficulty :/
