### ISSUE TITLE
getting error with aeon pool

### ISSUE THREAD

**Issue by aeon-team** [Snipa22/xmr-node-proxy#86]
Hello, I'm getting an error running proxy with aeon coin. Is there a way to fix it?

1|proxy    | 2017-12-24 10:11 +03:00: Received new block template from pool.aeon.team
1|proxy    | 2017-12-24 10:11 +03:00: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
1|proxy    |     at fromObject (buffer.js:262:9)
1|proxy    |     at Function.Buffer.from (buffer.js:101:10)
1|proxy    |     at new Buffer (buffer.js:80:17)
1|proxy    |     at new MasterBlockTemplate (/home/nodeproxy/xmr-node-proxy/lib/aeon.js:88:19)
1|proxy    |     at handleNewBlockTemplate (/home/nodeproxy/xmr-node-proxy/proxy.js:717:32)
1|proxy    |     at handlePoolMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:694:17)
1|proxy    |     at Socket.socket.on.e (/home/nodeproxy/xmr-node-proxy/proxy.js:657:17)
1|proxy    |     at emitOne (events.js:96:13)
1|proxy    |     at Socket.emit (events.js:188:7)
1|proxy    |     at readableAddChunk (_stream_readable.js:176:18)

**Comment by Snipa22** [comment]
This is not a nodejs-pool based pool.  Try something like https://aeonminingpool.com/
