### ISSUE TITLE
Install script change local time zone !?

### ISSUE THREAD

**Issue by KavkaTSR** [Snipa22/xmr-node-proxy#9]
Readme states that
> This script will install the proxy to whatever user it's running under!

But
```
echo "Etc/UTC" | sudo tee -a /etc/timezone
sudo rm -rf /etc/localtime
sudo ln -s /usr/share/zoneinfo/Zulu /etc/localtime
sudo dpkg-reconfigure -f noninteractive tzdata
```

It's worth mentioning that install script use "sudo" not only for "apt-get" and "systemd", but without changing systemwide time zone settings. It may be critical. At least it's worth mentioning in readme.

And the main question - is it possible to process time within proxy without changing systemwide time zone settings?

**Comment by Snipa22** [comment]
The system is designed to be installed on a clean box, where changing the timezone shouldn't matter.  As it stands though, no, the proxy is not time-sensitive, the bulk of that script simply was cut from the nodejs-pool installer, which is time sensitive.

**Comment by Snipa22** [comment]
Removed the auto UTC change.
