### ISSUE TITLE
How do I see the list of connections as well as the details of every connection?

### ISSUE THREAD

**Issue by louisitvn** [Snipa22/xmr-node-proxy#95]
I need to see a list of active connections as well as the statistics of every connection (hash rate for example)
It is very useful know individual worker performance

**Comment by Ethorsen** [comment]
Take a look at mike-teehan PR.  
https://github.com/Snipa22/xmr-node-proxy/pull/111

He's dumping a JSON file with workers info every 15sec on disk.  You can then retrieve that file for further analysis.

Or simply use its designed webpage for quick viewing
